name = "hiredtobe"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

dev.port = 8000

observability.logs.enabled = true

# Dev environment (API only, Vite serves frontend)
[env.dev]
name = "hiredtobe-dev"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "hiredtobe-db-dev"
database_id = "26efb6e8-622a-46e5-8f64-c94805273125"
migrations_dir = "migrations"

[env.dev.vars]
NODE_ENV = "development"
SESSION_SECRET = "Secrett"

# Production environment
[env.production]
name = "hiredtobe"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

[[env.production.d1_databases]]
binding = "DB"
database_name = "hiredtobe-db"
database_id = "e07e498c-ed39-4805-a813-212d6bf95456"
migrations_dir = "migrations"

[env.production.assets]
directory = "apps/client/dist"

[env.production.vars]
NODE_ENV = "production"
