name = "hiredtobe"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

dev.port = 8000

observability.logs.enabled = true

# Dev environment (API only, Vite serves frontend)
[env.dev]
name = "hiredtobe-dev"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "hiredtobe-db-dev"
database_id = "26efb6e8-622a-46e5-8f64-c94805273125"
migrations_dir = "migrations"


# Production environment
[env.production]
name = "hiredtobe"
main = "apps/server/src/index.ts"
compatibility_date = "2025-09-02"

[[env.production.d1_databases]]
binding = "DB"
# database_name = "hiredtobe-db-dev"
# database_id = "26efb6e8-622a-46e5-8f64-c94805273125"
database_name = "hiredtobe-db"
database_id = "e07e498c-ed39-4805-a813-212d6bf95456"
migrations_dir = "migrations"

[env.production.assets]
directory = "apps/client/dist"

[env.production.vars]
NODE_ENV = "production"

CLIENT_BASE_URI = "https://hiredtobe.kushagra-pyjs.workers.dev/"
# OAuth redirect URI
OAUTH_REDIRECT_ENDPOINT = "/api/auth/google/callback"

# Google Accounts API
GOOGLE_ACCOUNTS_URL = "https://accounts.google.com/o/oauth2/v2/auth"

# Google Base URLs
GOOGLE_API_BASE_URL = "https://www.googleapis.com"
GOOGLE_OAUTH_API_BASE_URL = "https://oauth2.googleapis.com"

# Google Scopes
GOOGLE_OAUTH_SCOPES = "openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"

# Google Endpoints
GOOGLE_OAUTH_TOKEN_ENDPOINT = "/token"
GOOGLE_API_USER_ENDPOINT = "/oauth2/v3/userinfo"
