name = "hiredtobe"
main = "app/server/src/index.ts"
compatibility_date = "2025-09-04"

dev.port = 8000

# Dev environment (API only, Vite serves frontend)
[env.dev]
name = "hiredtobe-dev"
main = "app/server/src/index.ts"
compatibility_date = "2025-09-04"

[env.dev.vars]
NODE_ENV = "development"
SESSION_SECRET = "Secrett"

# Production environment
[env.production]
name = "hiredtobe"
main = "app/server/src/index.ts"
compatibility_date = "2025-09-04"

[env.production.assets]
directory = "app/client/dist"

[env.production.vars]
NODE_ENV = "production"
